version: '3.9'

services:
  react-ts-app:
    build:
      context: ./react-ts-app
    container_name: react-ts-app
    volumes:
      - ./react-ts-app:/usr/app
      - nodemodules1:/usr/app/node_modules
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: /bin/sh -c "while sleep 1000; do :; done"
    network_mode: "host"

  react-ts-api:
    build:
      context: ./react-ts-api
    container_name: react-ts-api
    volumes:
      - ./react-ts-api:/usr/app
      - nodemodules2:/usr/app/node_modules
    command: "yarn start"
    network_mode: "host"

volumes:
    nodemodules1:
      driver: "local"
    nodemodules2:
      driver: "local"

# networks:
#   app-test:
#       driver: bridge
